services:
  shoutrrr:
    image: schornmd/shoutrrr
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./cron:/etc/cron.d # Cronjobs
      - ./logs:/var/log    # Logging
      - ./opt:/opt         # Scripts